name: 'auto-hms-action'
description: 'GitHub Action for Automation of NU-HMS'

inputs:
  SCHOOL_ID:
    description: 'School ID at Nagasaki University'
    required:    true
    default:     'bb12345678'
  SCHOOL_PASSWD:
    description: 'Password of School ID at Nagasaki University'
    required:    true
    default:     'passwd'

runs:
  using: 'composite'
  steps:
    - shell: bash
      id: setup
      run: |
        sudo apt --quiet update
        sudo apt --quiet autoremove -y
        sudo apt --quiet install -y fonts-ipafont-gothic
        sudo apt --quiet install -y python3
        sudo python3 -m pip install --quiet selenium
        sudo apt --quiet install -y chromium-chromedriver

    - shell: bash
      id: automation
      run: |
        cd ${{ github.action_path }}
        python3 automation.py ${{ inputs.SCHOOL_ID }} ${{ inputs.SCHOOL_PASSWD }}

