name: 'auto-hms-action'
description: 'GitHub Action for Automation of NU-HMS'

inputs:
  ID:
    description: 'School ID at Nagasaki University'
    required:    true
    default:     'bb12345678'
  PASSWORD:
    description: 'Password of School ID at Nagasaki University'
    required:    true
    default:     'passwd'

runs:
  using: 'composite'
  steps:
    - shell: bash
      id: setup
      run: |
        sudo apt update > /dev/null 2>&1
        sudo apt autoremove -y > /dev/null 2>&1
        sudo apt install -y fonts-ipafont-gothic > /dev/null 2>&1
        sudo apt install -y python3 > /dev/null 2>&1
        sudo python3 -m pip install selenium > /dev/null 2>&1
        sudo apt install -y chromium-chromedriver > /dev/null 2>&1

    - shell: bash
      id: automation
      run: |
        cd ${{ github.action_path }}
        ls -al
        python3 automation.py ${{ inputs.ID }} ${{ inputs.PASSWORD }}
