name: GitHub Action for keeping a cronjob trigger.

on:
  schedule:
    - cron: '0 22 */50 * *'
  workflow_dispatch:

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Keep alive for a cronjob trigger
        run: |
          git config --global user.email "someone@sample.com"
          git config --global user.name "Keepalive Action"
          git commit --verbose --allow-empty -m ":robot: Empty commit"
          git push --verbose https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git

