name: "Keepalive Action"

on:
  schedule:
    - cron: '0 22 * */1 *'
  workflow_dispatch:

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Keepalive Action"
        uses: k5-mot/keepalive-action@main
        with:
          GITHUB_TOKEN: ${{env.GITHUB_TOKEN}}

